[platformio]
default_envs = wt32-eth01

[env:wt32-eth01]
platform = espressif32
board = wt32-eth01
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
lib_deps =
  olikraus/U8g2
  adafruit/Adafruit SHT31 Library
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  bblanchon/ArduinoJson
  knolleary/PubSubClient
